### PR TITLE
exchange reflection field access with mixin accessors

### PR DESCRIPTION
**Pull request by Alexdoru**

### CODE REVIEW

**Review by glowredman — COMMENTED** [review]
Have you measured any performance improvements? Otherwise I don't really see the point in changing it.

**Comment by Alexdoru** [comment]
The mod already has mixins targeting the same classes. It's about making the code clean + This way when we look at the class dump, we know which mod is interacting with those fields.

**Comment by Alexdoru** [comment]
Also it's using reflection to access a field that was created via mixins... that's not how you properly use mixins

**Review by mitchej123 — APPROVED** [review]
I'm a fan of accessors over reflection.  Speed or not it generally reads nicer.

**Comment by Alexdoru** [comment]
> I'm a fan of accessors over reflection. Speed or not it generally reads nicer.

I am a fan too

**Pull request merged**
